# .readthedocs.yaml
# Required configuration file for Read the Docs

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - method: pip
      requirements: docs/requirements.txt  # Or use environment.yml
      extra_requirements:
        - docs

sphinx:
  configuration: docs/source/conf.py
